### ISSUE TITLE
pathname not set when watching files

### ISSUE THREAD

**Issue by quotquot** [ldo/inotipy#1]
During development, I need to watch certain files (not directories) that change and reload them. `inotipy` does see the changes to these files but does not provide the name of the file that changed, which forces me to either watch the directories in which these files are and filter on the filename, or have one watcher per file. It would be more intuitive to have only one watcher for all these files and get the name of the file that indeed changed.

A basic example:
* create two files `foo` and `bar` in `/tmp`:
```shell
$ echo 1 > /tmp/foo
$ echo 2 > /tmp/bar 
```
* run a watcher for these two files:
```python
import sys
import asyncio
import inotify

async def mainline() :
    watcher = inotify.Watcher.create()
    for path in  ('/tmp/foo','/tmp/bar'):
        watcher.watch(path, inotify.IN.ALL_EVENTS)
    while True :
        event = await watcher.get()
        sys.stdout.write("Got event: %s\n" % repr(event))

loop = asyncio.get_event_loop()
loop.run_until_complete(mainline())
```
* change the content of the files:
```shell
$ echo 3 > /tmp/foo 
$ echo 4 > /tmp/bar 
```
* see that we cannot tell which file actually changed:
```
Got event: Event(1, 0x00000002[<EVENT_BIT.MODIFY: 1>], 0, '')
Got event: Event(1, 0x00000020[<EVENT_BIT.OPEN: 5>], 0, '')
Got event: Event(1, 0x00000002[<EVENT_BIT.MODIFY: 1>], 0, '')
Got event: Event(1, 0x00000008[<EVENT_BIT.CLOSE_WRITE: 3>], 0, '')
Got event: Event(2, 0x00000002[<EVENT_BIT.MODIFY: 1>], 0, '')
Got event: Event(2, 0x00000020[<EVENT_BIT.OPEN: 5>], 0, '')
Got event: Event(2, 0x00000002[<EVENT_BIT.MODIFY: 1>], 0, '')
Got event: Event(2, 0x00000008[<EVENT_BIT.CLOSE_WRITE: 3>], 0, '')
```

**Comment by quotquot** [comment]
Silly me. The changed file is 1 and 2. Sorry. I focused on pathname and did not pay attention to the first parameter... Maybe pass the name of the file as pathname anyway so that we do not have to keep track of the order in which paths were added?

**Comment by ldo** [comment]
The Event returned includes a reference to the Watch object, which contains the path that you passed when creating it.
